### ISSUE TITLE
Not working on Spigot 1.20.2 

### ISSUE THREAD

**Issue by p0ns** [Fulminazzo/TeleportEffects#1]
I get this error when trying to toggle

```
[14:07:11] [Server thread/INFO]: holap0ns issued server command: /toggleteleporteffects
[14:07:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'toggleteleporteffects' in plugin TeleportEffects v2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:879) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:320) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:304) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1827) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1789) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1133) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1112) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1105) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:115) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1088) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "it.fulminazzo.teleporteffects.TeleportEffects.getLang()" because the return value of "it.fulminazzo.teleporteffects.TeleportEffects.getPlugin()" is null
        at it.fulminazzo.teleporteffects.Enums.Message.getMessage(Message.java:25) ~[?:?]
        at it.fulminazzo.teleporteffects.Commands.ToggleTeleportEffects.onCommand(ToggleTeleportEffects.java:30) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

```

When teleporting

```
[14:12:59] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to TeleportEffects v2.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.teleport(CraftPlayer.java:923) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportSync.teleportAsync(AsyncTeleportSync.java:13) ~[?:?]
        at com.earth2me.essentials.paperlib.environments.Environment.teleport(Environment.java:101) ~[?:?]
        at com.earth2me.essentials.paperlib.PaperLib.teleportAsync(PaperLib.java:88) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.lambda$nowAsync$3(AsyncTeleport.java:219) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.nowAsync(AsyncTeleport.java:190) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.teleport(AsyncTeleport.java:292) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.warp(AsyncTeleport.java:441) ~[?:?]
        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:99) ~[?:?]
        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:45) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:170) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:820) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:723) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:879) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:320) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:304) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1827) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1789) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1133) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1112) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1105) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1089) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3911-Spigot-e0e223f-71b0135]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "it.fulminazzo.teleporteffects.Interfaces.IBearPlugin.getConfiguration()" because "this.plugin" is null
        at it.fulminazzo.teleporteffects.Enums.BearConfigOption.getStringList(BearConfigOption.java:36) ~[?:?]
        at it.fulminazzo.teleporteffects.Enums.ConfigOption.getTeleportCauses(ConfigOption.java:41) ~[?:?]
        at it.fulminazzo.teleporteffects.Listeners.PlayerListener.onPlayerTeleport(PlayerListener.java:39) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 43 more
```

**Comment by fulminazzo** [comment]
Hey there!
First of all, thank you so much for letting me know of the issue. 
Apparently I made some mistakes while preparing the API for the plugin, but it is all been fixed in the [new release](https://github.com/Fulminazzo/TeleportEffects/releases/tag/2.1).
